version: '2'
services:
  web:
    build: .
    volumes:
      - ../../:/opt/moqui
      #- "../../execwartmp:/opt/moqui/execwartmp"
    links:
      - moqui-database
      - elasticsearch
    environment:
      - entity_ds_db_conf=mysql8
      - entity_ds_host=moqui-database
      - entity_ds_port=3306
      - entity_ds_database=moqui
      # NOTE: using root user because for TX recovery MySQL requires the 'XA_RECOVER_ADMIN' and in version 8 that must be granted explicitly
      - entity_ds_user=root
      - entity_ds_password=moquiroot
      - entity_ds_crypt_pass='MoquiDefaultPassword:CHANGEME'
      # configuration for ElasticFacade.ElasticClient, make sure moqui-elasticsearch is NOT included in the Moqui build
      - elasticsearch_url=http://elasticsearch:9200
      # hazelcast multicast setup
      - hazelcast_multicast_enabled=true
      - hazelcast_multicast_group=224.2.2.3
      - hazelcast_multicast_port=54327
      - hazelcast_group_name=test
      - hazelcast_group_password=test-pass
  lb:
    image: dockercloud/haproxy
    links:
      - web
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  moqui-database:
    image: mysql:8.0
    container_name: moqui-database
    restart: always
    ports:
      # change this as needed to bind to any address or even comment to not expose port outside containers
      - 127.0.0.1:3306:3306
    volumes:
      # edit these as needed to map configuration and data storage
      - ./db/mysql/data:/var/lib/mysql
      # - /my/mysql/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=moquiroot
      - MYSQL_DATABASE=moqui
      - MYSQL_USER=moqui
      - MYSQL_PASSWORD=moqui
  elasticsearch:
    # very important: use the '-oss' version otherwise x-pack is included and because of licensing, etc moqui instances can't join the cluster
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.2
    container_name: elasticsearch
    # command: elasticsearch
    restart: always
    ports:
      # change this as needed to bind to any address or even comment to not expose port outside containers
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    #volumes:
      # edit these as needed to map configuration and data storage
      # - ./elasticsearch/data:/usr/share/elasticsearch/data
      # - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      # - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - discovery.type=single-node
      - network.host=_site_